spring.application.name=cooking-backend

server.port=8082
spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/cookbook?autoReconnect=true&allowPublicKeyRetrieval=true&useAffectedRows=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8 
spring.datasource.username=root
spring.datasource.password=123456

logging.level.root=info
logging.level.org.springframework.web=INFO
logging.level.com.cooking=debug

mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.cooking.core.entity
mybatis-plus.configuration.mapUnderscoreToCamelCase=true
mybatis-plus.configuration.database-id=


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

#文件访问根地址
upload.url=http://127.0.0.1:8080
#文件存放根路径
upload.path=E:/cooking_upload
